package com.techm.brms.itemcityrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ItemCity implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.math.BigDecimal localTax;
   private java.math.BigDecimal sellPrice;

   public ItemCity()
   {
   }

   public java.math.BigDecimal getLocalTax()
   {
      return this.localTax;
   }

   public void setLocalTax(java.math.BigDecimal localTax)
   {
      this.localTax = localTax;
   }

   public java.math.BigDecimal getSellPrice()
   {
      return this.sellPrice;
   }

   public void setSellPrice(java.math.BigDecimal sellPrice)
   {
      this.sellPrice = sellPrice;
   }

   public ItemCity(java.math.BigDecimal localTax,
         java.math.BigDecimal sellPrice)
   {
      this.localTax = localTax;
      this.sellPrice = sellPrice;
   }

}