package com.techm.brms.itemcityrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ItemCity implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ItemCity() {
    }

}