package com.techm.brms.discountrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private double discount;
   private int amount;

   public OrderDO()
   {
   }

   public double getDiscount()
   {
      return this.discount;
   }

   public void setDiscount(double discount)
   {
      this.discount = discount;
   }

   public int getAmount()
   {
      return this.amount;
   }

   public void setAmount(int amount)
   {
      this.amount = amount;
   }

   public OrderDO(double discount, int amount)
   {
      this.discount = discount;
      this.amount = amount;
   }

}