package com.techm.brms.discountrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrderDO() {
    }

}