package com.techm.brms.driverriskrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DriverDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DriverDO() {
    }

}